export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const REMOVE_ACTIVE_CATEGORY = 'REMOVE_ACTIVE_CATEGORY';



